# Generated by Django 4.2.7 on 2025-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_admin_to_agronomist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('agronomist', 'Agronomist'), ('farm_user', 'Farm User')], default='farm_user', max_length=20),
        ),
    ]
