# Generated by Django 4.2.7 on 2025-09-01 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=200)),
                ('variety', models.CharField(max_length=200)),
                ('batch_code', models.CharField(max_length=100)),
                ('transplant_date', models.DateField()),
                ('current_stage', models.CharField(choices=[('germination', 'Germination'), ('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvest', 'Harvest')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'crop_name'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('size_in_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_farms', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='assigned_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SprayIrrigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_type', models.CharField(choices=[('spray', 'Spray'), ('irrigation', 'Irrigation')], max_length=20)),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('chemical_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('sprayer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('irrigation_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('irrigation_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spray_irrigation_logs', to='farms.cropstage')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spray_irrigation_logs', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Fertigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_zone_name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('operator_name', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ec_before', models.DecimalField(decimal_places=2, help_text='EC Before (mS/cm)', max_digits=5)),
                ('ph_before', models.DecimalField(decimal_places=2, help_text='pH Before', max_digits=4)),
                ('ec_after', models.DecimalField(decimal_places=2, help_text='EC After (mS/cm)', max_digits=5)),
                ('ph_after', models.DecimalField(decimal_places=2, help_text='pH After', max_digits=4)),
                ('water_volume', models.DecimalField(decimal_places=2, help_text='Water Volume (L)', max_digits=8)),
                ('nutrients_used', models.JSONField(default=list, help_text='List of nutrients with product name and quantity')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.cropstage')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertigations', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('farm_hygiene', models.BooleanField(default=False)),
                ('disease_pest_check', models.BooleanField(default=False)),
                ('daily_crop_update', models.BooleanField(default=False)),
                ('trellising', models.BooleanField(default=False)),
                ('spraying', models.BooleanField(default=False)),
                ('cleaning', models.BooleanField(default=False)),
                ('pruning', models.BooleanField(default=False)),
                ('main_tank_ec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('main_tank_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dripper_ec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dripper_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-date'],
            },
        ),
        migrations.AddField(
            model_name='cropstage',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_stages', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('issue', 'Issue')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date', '-created_at'],
                'indexes': [models.Index(fields=['farm_user', '-assigned_date'], name='farms_worke_farm_us_a2d24b_idx'), models.Index(fields=['status'], name='farms_worke_status_68b231_idx'), models.Index(fields=['-created_at'], name='farms_worke_created_c9dae8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('daily_task', 'Daily Task Submission'), ('farm_created', 'Farm Created'), ('user_created', 'User Created'), ('harvest_due', 'Harvest Due'), ('harvest_overdue', 'Harvest Overdue'), ('harvest_reminder', 'Harvest Reminder'), ('fertigation_due', 'Fertigation Due'), ('fertigation_overdue', 'Fertigation Overdue'), ('general', 'General')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='farms_notif_user_id_58b1b7_idx'), models.Index(fields=['farm', '-created_at'], name='farms_notif_farm_id_880b96_idx'), models.Index(fields=['notification_type'], name='farms_notif_notific_e706be_idx'), models.Index(fields=['is_read'], name='farms_notif_is_read_3be001_idx'), models.Index(fields=['due_date'], name='farms_notif_due_dat_6a5c0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_zone', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_type', models.CharField(choices=[('pest', 'Pest'), ('disease', 'Disease'), ('nutrient_deficiency', 'Nutrient Deficiency'), ('equipment_malfunction', 'Equipment Malfunction'), ('water_leak', 'Water Leak'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='issue_reports/')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('farm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm_user', '-created_at'], name='farms_issue_farm_us_cf0efb_idx'), models.Index(fields=['admin_user'], name='farms_issue_admin_u_01c477_idx'), models.Index(fields=['status'], name='farms_issue_status_8ccae5_idx'), models.Index(fields=['severity'], name='farms_issue_severit_61f416_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['created_by'], name='farms_farm_created_d61187_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['is_active'], name='farms_farm_is_acti_0f0498_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['-created_at'], name='farms_farm_created_7249f7_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['user', '-date'], name='farms_daily_user_id_ab5439_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['farm', '-date'], name='farms_daily_farm_id_e86f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['-created_at'], name='farms_daily_created_5149d4_idx'),
        ),
    ]
