# Generated by Django 4.2.7 on 2025-09-02 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='farms.farm'),
        ),
        migrations.CreateModel(
            name='SpraySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spray_id', models.CharField(help_text='Unique spray identifier', max_length=50, unique=True)),
                ('crop_zone', models.CharField(help_text='Crop/Zone identifier', max_length=200)),
                ('date_time', models.DateTimeField(help_text='Date & Time of spray application')),
                ('product_used', models.CharField(help_text='Product/Chemical used', max_length=300)),
                ('dose_concentration', models.CharField(help_text='Dose/Concentration applied', max_length=200)),
                ('reason', models.CharField(choices=[('pest', 'Pest Control'), ('disease', 'Disease Control'), ('nutrient', 'Nutrient Application')], help_text='Reason for spray application', max_length=20)),
                ('phi_log', models.PositiveIntegerField(help_text='Pre-Harvest Interval in days')),
                ('worker_name', models.CharField(help_text='Name of worker who applied spray', max_length=200)),
                ('next_spray_reminder', models.DateTimeField(blank=True, help_text='Next spray reminder date', null=True)),
                ('weather_conditions', models.CharField(blank=True, help_text='Weather conditions during application', max_length=200, null=True)),
                ('application_method', models.CharField(blank=True, help_text='Spray application method', max_length=100, null=True)),
                ('equipment_used', models.CharField(blank=True, help_text='Equipment/sprayer used', max_length=200, null=True)),
                ('area_covered', models.DecimalField(blank=True, decimal_places=2, help_text='Area covered in acres', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('image_data', models.TextField(blank=True, help_text='Base64 encoded image evidence', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.cropstage')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spray_schedules', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time', '-created_at'],
                'indexes': [models.Index(fields=['farm', '-date_time'], name='farms_spray_farm_id_7e293a_idx'), models.Index(fields=['user', '-date_time'], name='farms_spray_user_id_8959d7_idx'), models.Index(fields=['reason'], name='farms_spray_reason_da622c_idx'), models.Index(fields=['next_spray_reminder'], name='farms_spray_next_sp_910f9c_idx'), models.Index(fields=['is_completed'], name='farms_spray_is_comp_563342_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('daily_task', 'Daily Task Submission'), ('issue_report', 'Issue Report'), ('farm_user_created', 'Farm User Created'), ('farm_created', 'Farm Created'), ('system_alert', 'System Alert'), ('general', 'General')], default='general', max_length=20)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('source_farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.farm')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='farms_admin_admin_u_a6618b_idx'), models.Index(fields=['notification_type'], name='farms_admin_notific_f87752_idx'), models.Index(fields=['is_read'], name='farms_admin_is_read_140ca6_idx')],
            },
        ),
    ]
