# Generated by Django 4.2.7 on 2025-09-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_issuereport_farm_sprayschedule_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropstage',
            name='actual_harvest_date',
            field=models.DateField(blank=True, help_text='Actual harvest completion date', null=True),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='actual_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield harvested in kg/units', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='expected_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield in kg/units', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='farm_section',
            field=models.CharField(blank=True, help_text='Farm section or hydroponic unit', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('moderate', 'Moderate'), ('needs_attention', 'Needs Attention')], default='healthy', max_length=20),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='issues_reported',
            field=models.TextField(blank=True, help_text='Pests, diseases, nutrient deficiency', null=True),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='losses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yield losses in kg/units', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='sowing_date',
            field=models.DateField(blank=True, help_text='Date of sowing seeds', null=True),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='stage_end_date',
            field=models.DateField(blank=True, help_text='When current stage ended/expected to end', null=True),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='stage_start_date',
            field=models.DateField(blank=True, help_text='When current stage started', null=True),
        ),
        migrations.AlterField(
            model_name='cropstage',
            name='notes',
            field=models.TextField(blank=True, help_text='General observations and notes', null=True),
        ),
        migrations.AlterField(
            model_name='cropstage',
            name='transplant_date',
            field=models.DateField(help_text='Date of transplanting'),
        ),
        migrations.AddIndex(
            model_name='cropstage',
            index=models.Index(fields=['user', '-created_at'], name='farms_crops_user_id_013c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='cropstage',
            index=models.Index(fields=['farm', 'current_stage'], name='farms_crops_farm_id_03eb43_idx'),
        ),
        migrations.AddIndex(
            model_name='cropstage',
            index=models.Index(fields=['batch_code'], name='farms_crops_batch_c_fed09a_idx'),
        ),
        migrations.AddIndex(
            model_name='cropstage',
            index=models.Index(fields=['health_status'], name='farms_crops_health__367171_idx'),
        ),
    ]
