# Generated by Django 4.2.7 on 2025-09-09 19:38

from django.db import migrations

def set_default_health_status(apps, schema_editor):
    """Set default health_status for existing CropStage records"""
    CropStage = apps.get_model('farms', 'CropStage')
    CropStage.objects.filter(health_status__isnull=True).update(health_status='healthy')
    CropStage.objects.filter(health_status='').update(health_status='healthy')

def reverse_set_default_health_status(apps, schema_editor):
    """Reverse migration - do nothing"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_cropstage_actual_harvest_date_cropstage_actual_yield_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_health_status, reverse_set_default_health_status),
    ]
