# Generated by Django 4.2.7 on 2025-09-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_auto_20250910_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropstage',
            name='actual_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield harvested in kg/units (filled after harvest)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cropstage',
            name='losses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Yield losses in kg/units', max_digits=8, null=True),
        ),
    ]
