# Generated by Django 4.2.7 on 2025-09-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_alter_cropstage_actual_yield_alter_cropstage_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropstage',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area in acres/hectares', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cropstage',
            name='number_of_plants',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of plants', null=True),
        ),
    ]
