# Generated by Django 4.2.7 on 2025-09-09 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0006_cropstage_area_cropstage_number_of_plants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], max_length=20)),
                ('wage_per_day', models.DecimalField(decimal_places=2, help_text='Daily wage amount', max_digits=8)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='workertask',
            name='farms_worke_farm_us_a2d24b_idx',
        ),
        migrations.RemoveIndex(
            model_name='workertask',
            name='farms_worke_status_68b231_idx',
        ),
        migrations.RemoveField(
            model_name='workertask',
            name='farm_user',
        ),
        migrations.RemoveField(
            model_name='workertask',
            name='issue_description',
        ),
        migrations.RemoveField(
            model_name='workertask',
            name='worker_name',
        ),
        migrations.AddField(
            model_name='workertask',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes when task is completed', null=True),
        ),
        migrations.AddField(
            model_name='workertask',
            name='due_date',
            field=models.DateField(blank=True, help_text='Expected completion date', null=True),
        ),
        migrations.AddField(
            model_name='workertask',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_tasks', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='workertask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_worker_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workertask',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or comments', null=True),
        ),
        migrations.AlterField(
            model_name='workertask',
            name='task_description',
            field=models.TextField(help_text='Description of the assigned task'),
        ),
        migrations.AddField(
            model_name='worker',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workertask',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farms.worker'),
        ),
        migrations.AddIndex(
            model_name='workertask',
            index=models.Index(fields=['user', '-assigned_date'], name='farms_worke_user_id_e24c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='workertask',
            index=models.Index(fields=['worker', 'status'], name='farms_worke_worker__f2b832_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['user', 'farm'], name='farms_worke_user_id_7e8e68_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['employment_type'], name='farms_worke_employm_6a5895_idx'),
        ),
    ]
