# Generated by Django 4.2.7 on 2025-09-09 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0007_worker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(help_text='Brief description of the expense', max_length=200)),
                ('category', models.CharField(choices=[('seeds_plants', 'Seeds/Plants'), ('fertilizers', 'Fertilizers'), ('pesticides', 'Pesticides/Chemicals'), ('equipment', 'Equipment/Tools'), ('labor', 'Labor'), ('irrigation', 'Irrigation/Water'), ('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('packaging', 'Packaging'), ('marketing', 'Marketing'), ('others', 'Others')], help_text='Type of expense', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cheque', 'Cheque'), ('others', 'Others')], help_text='How the payment was made', max_length=20)),
                ('expense_date', models.DateField(help_text='Date when the expense was made')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or details', null=True)),
                ('bill_number', models.CharField(blank=True, help_text='Bill/Invoice number', max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, help_text='Supplier/Vendor name', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_expenditures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['farm', '-expense_date'], name='farms_expen_farm_id_45d655_idx'), models.Index(fields=['user', '-expense_date'], name='farms_expen_user_id_a72f67_idx'), models.Index(fields=['category'], name='farms_expen_categor_0a343f_idx'), models.Index(fields=['payment_method'], name='farms_expen_payment_24b6f3_idx'), models.Index(fields=['-created_at'], name='farms_expen_created_de0826_idx')],
            },
        ),
    ]
