# Generated by Django 4.2.7 on 2025-09-09 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0008_expenditure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='Name of the crop sold', max_length=200)),
                ('batch_code', models.CharField(help_text='Unique batch identifier for traceability', max_length=100)),
                ('quantity_sold', models.DecimalField(decimal_places=3, help_text='Quantity of crop sold', max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('gram', 'Gram (g)'), ('ton', 'Ton'), ('piece', 'Piece'), ('box', 'Box'), ('bag', 'Bag'), ('crate', 'Crate'), ('bunch', 'Bunch')], default='kg', help_text='Unit of measurement', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total sale amount', max_digits=12)),
                ('buyer_name', models.CharField(help_text='Name of the buyer', max_length=200)),
                ('buyer_contact', models.CharField(blank=True, help_text='Buyer contact number', max_length=20, null=True)),
                ('buyer_address', models.TextField(blank=True, help_text='Buyer address', null=True)),
                ('sale_date', models.DateField(help_text='Date when the sale was made')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('payment_due_date', models.DateField(blank=True, help_text='Expected payment completion date', null=True)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, help_text='Amount already received', max_digits=12)),
                ('quality_grade', models.CharField(blank=True, help_text='Quality grade of the crop', max_length=50, null=True)),
                ('transportation_cost', models.DecimalField(decimal_places=2, default=0, help_text='Transportation cost', max_digits=8)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Commission/brokerage amount', max_digits=8)),
                ('notes', models.TextField(blank=True, help_text='Additional sale notes', null=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice/bill number', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
                'indexes': [models.Index(fields=['farm', '-sale_date'], name='farms_sale_farm_id_db0bf2_idx'), models.Index(fields=['user', '-sale_date'], name='farms_sale_user_id_5b7730_idx'), models.Index(fields=['payment_status'], name='farms_sale_payment_2eb92a_idx'), models.Index(fields=['crop_name'], name='farms_sale_crop_na_b265db_idx'), models.Index(fields=['buyer_name'], name='farms_sale_buyer_n_2fe9cf_idx'), models.Index(fields=['-created_at'], name='farms_sale_created_8c7916_idx')],
            },
        ),
    ]
