# Generated by Django 4.2.7 on 2025-09-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quantity of crop sold', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total sale amount', max_digits=12),
        ),
    ]
