# Generated by Django 4.2.7 on 2025-09-11 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0010_alter_sale_price_per_unit_alter_sale_quantity_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_farm_wide',
            field=models.BooleanField(default=False, help_text='True if notification is for all farm users, False for specific user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('daily_task', 'Daily Task Submission'), ('farm_created', 'Farm Created'), ('user_created', 'User Created'), ('harvest_due', 'Harvest Due'), ('harvest_overdue', 'Harvest Overdue'), ('harvest_reminder', 'Harvest Reminder'), ('fertigation_due', 'Fertigation Due'), ('fertigation_overdue', 'Fertigation Overdue'), ('admin_message', 'Admin Message'), ('farm_announcement', 'Farm Announcement'), ('task_reminder', 'Task Reminder'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_by', '-created_at'], name='farms_notif_created_c3d698_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_farm_wide'], name='farms_notif_is_farm_f5c3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='farms_notif_priorit_7404e1_idx'),
        ),
    ]
