# Generated by Django 4.2.7 on 2025-09-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0012_plantdiseaseprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdiseaseprediction',
            name='image_format',
            field=models.CharField(blank=True, help_text='Image format (jpeg, png, etc.)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plantdiseaseprediction',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='plantdiseaseprediction',
            name='image_size_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='Image size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='plantdiseaseprediction',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
    ]
