# Generated by manual fix for photo_evidence field consistency

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0014_alter_notification_notification_type_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='photo_evidence',
            field=models.TextField(blank=True, null=True, help_text="Base64 encoded image evidence"),
        ),
    ]