# Generated by Django migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0014_alter_notification_notification_type_calendarevent'),
    ]

    operations = [
        # First, remove the old indexes that reference admin_user
        migrations.RemoveIndex(
            model_name='issuereport',
            name='farms_issue_admin_u_01c477_idx',
        ),
        migrations.RemoveIndex(
            model_name='adminnotification',
            name='farms_admin_admin_u_a6618b_idx',
        ),

        # Rename AdminNotification model to AgronomistNotification
        migrations.RenameModel(
            old_name='AdminNotification',
            new_name='AgronomistNotification',
        ),

        # Rename admin_user field to agronomist_user in IssueReport
        migrations.RenameField(
            model_name='issuereport',
            old_name='admin_user',
            new_name='agronomist_user',
        ),

        # Rename admin_user field to agronomist_user in AgronomistNotification
        migrations.RenameField(
            model_name='agronomistnotification',
            old_name='admin_user',
            new_name='agronomist_user',
        ),

        # Add the new indexes with the correct field names
        migrations.AddIndex(
            model_name='issuereport',
            index=models.Index(fields=['agronomist_user'], name='farms_issue_agron_u_01c477_idx'),
        ),
        migrations.AddIndex(
            model_name='agronomistnotification',
            index=models.Index(fields=['agronomist_user', '-created_at'], name='farms_agron_agron_u_a6618b_idx'),
        ),
    ]