# Generated by Django 4.2.7 on 2025-09-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0015_fix_issuereport_photo_evidence'),
        ('farms', '0015_rename_admin_to_agronomist'),
    ]

    operations = [
    ]
