# Generated by Django migration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0016_merge_20250927_2327'),
    ]

    operations = [
        # First, remove all indexes from CalendarEvent to avoid field reference errors
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='farms_calen_farm_id_2be712_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='farms_calen_created_c4dc5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='farms_calen_event_t_428c9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='farms_calen_status_bca0c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='farms_calen_priorit_268ffc_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='farms_calen_start_d_c6cd05_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='farms_calen_recurre_79f1f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='farms_calen_enable__9ec4ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='calendarevent',
            name='farms_calen_created_b76e1d_idx',
        ),

        # Now remove fields from CalendarEvent
        migrations.RemoveField(
            model_name='calendarevent',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='parent_event',
        ),

        # Update notification type choices to use agronomist instead of admin
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('daily_task', 'Daily Task Submission'), ('farm_created', 'Farm Created'), ('user_created', 'User Created'), ('harvest_due', 'Harvest Due'), ('harvest_overdue', 'Harvest Overdue'), ('harvest_reminder', 'Harvest Reminder'), ('fertigation_due', 'Fertigation Due'), ('fertigation_overdue', 'Fertigation Overdue'), ('admin_message', 'Agronomist Message'), ('agronomist_message', 'Agronomist Message'), ('farm_announcement', 'Farm Announcement'), ('task_reminder', 'Task Reminder'), ('general', 'General')], default='general', max_length=20),
        ),

        # Finally, delete the CalendarEvent model
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]