# Generated by Django 4.2.7 on 2025-09-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0017_remove_calendarevent_indexes_and_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agronomistnotification',
            new_name='farms_agron_agronom_610fed_idx',
            old_name='farms_agron_agron_u_a6618b_idx',
        ),
        migrations.RenameIndex(
            model_name='agronomistnotification',
            new_name='farms_agron_notific_ed3a66_idx',
            old_name='farms_admin_notific_f87752_idx',
        ),
        migrations.RenameIndex(
            model_name='agronomistnotification',
            new_name='farms_agron_is_read_45e0fa_idx',
            old_name='farms_admin_is_read_140ca6_idx',
        ),
        migrations.RenameIndex(
            model_name='issuereport',
            new_name='farms_issue_agronom_d9e62e_idx',
            old_name='farms_issue_agron_u_01c477_idx',
        ),
        migrations.AlterField(
            model_name='agronomistnotification',
            name='agronomist_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agronomist_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agronomistnotification',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_agronomist_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='photo_evidence',
            field=models.ImageField(blank=True, null=True, upload_to='issue_reports/'),
        ),
    ]
