# Generated by Django 4.2.7 on 2025-10-01 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0018_rename_farms_agron_agron_u_a6618b_idx_farms_agron_agronom_610fed_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of the task', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was marked as completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_tasks', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'user', '-created_at'], name='farms_farmt_farm_id_40f309_idx'), models.Index(fields=['user', 'status'], name='farms_farmt_user_id_a807cb_idx'), models.Index(fields=['farm', 'status'], name='farms_farmt_farm_id_37d167_idx'), models.Index(fields=['due_date'], name='farms_farmt_due_dat_a0dede_idx'), models.Index(fields=['-created_at'], name='farms_farmt_created_7f14b4_idx')],
            },
        ),
    ]
