# Generated by Django 4.2.7 on 2025-10-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0019_farmtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmtask',
            name='photo_attachment',
            field=models.ImageField(blank=True, help_text='Optional photo attachment for task documentation', null=True, upload_to='farm_tasks/'),
        ),
    ]
