# Generated by Django 4.2.7 on 2025-10-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0020_add_photo_attachment_to_farmtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmtask',
            name='photo_attachment',
        ),
        migrations.AddField(
            model_name='farmtask',
            name='image_data',
            field=models.TextField(blank=True, help_text='Base64 encoded image evidence', null=True),
        ),
    ]
